# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mccme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProblems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=0)),
                ('plabel', models.CharField(default=b'noname', max_length=300)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=0)),
                ('uname', models.CharField(default=b'noname', max_length=200)),
                ('tcount', models.IntegerField(default=0)),
                ('solved_problems', models.ManyToManyField(related_name='solved_problems', to='mccme.Problem')),
                ('unsolved_problems', models.ManyToManyField(related_name='unsolved_problems', to='mccme.Problem')),
            ],
        ),
    ]
